services:
  mumble:
    image: mumblevoip/mumble-server:v1.4.287-4
    container_name: mumble
    restart: unless-stopped
    entrypoint: /usr/bin/mumble-server
    command: "-fg -ini /data/murmur.ini"
    environment:
      - MUMBLE_SUPW=adminpass  # replace with your desired SuperUser password
    ports:
      - "64738:64738/tcp"
      - "64738:64738/udp"
    volumes:
      - ./murmur.ini:/data//murmur.ini
      - mumble-data:/data

  mumble-auto-afk:
    image: github.com/huxcrux/mumble-auto-afk:latest
    container_name: mumble-auto-afk
    restart: always
    network_mode: "service:mumble"
    environment:
      - MUMBLE_AFK_IDLE_THRESHOLD=30
      - MUMBLE_AFK_CHANNEL_ID=1
      - MUMBLE_SERVER_HOST=localhost
      - MUMBLE_ICE_PORT=6502
      - MUMBLE_ICE_SECRET=supersecretpass
    depends_on:
      - mumble

volumes:
  mumble-data:
