name: CI

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:

jobs:
  build-api:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set envs
      run: |
        echo "GITHUB_REPO=${GITHUB_REPOSITORY}" >> $GITHUB_ENV
        if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
          echo "DOCKER_TAG=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
        elif [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
          echo "DOCKER_TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
        else
          # sanitize branch name (remove slashes)
          SAFE_BRANCH=$(echo "${GITHUB_REF_NAME}" | sed 's#/##g')
          echo "DOCKER_TAG=${SAFE_BRANCH}" >> $GITHUB_ENV
        fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      if: startsWith(github.ref, 'refs/tags/v')
      uses: docker/login-action@v3
      with:
        registry: ghcr.io/huxcrux
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build (only pushes on semver tags)
      uses: docker/build-push-action@v6
      with:
        context: .
        no-cache: true
        file: ./Dockerfile
        push: ${{ startsWith(github.ref, 'refs/tags/v') }}
        tags: |
          ghcr.io/${{ env.GITHUB_REPO }}:${{ env.DOCKER_TAG }}
          ghcr.io/${{ env.GITHUB_REPO }}:latest
        secrets: |
          "netrc=machine github.com login ${{secrets.GO_DEP_SECRETS}}"
